"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowRightLeft, Save } from "lucide-react";
import { topicLabels, dialogueMode, type Session, type SessionState } from "@/lib/ai/schema";
import type { ConversationEntry } from "@/lib/ai/messages";
import { ConversationEntries } from "@/components/ai/ConversationHistory";
import DraftPreview from "@/components/ai/DraftPreview";

type Member = {id:string;display_name:string|null};
type Event = {id:string;action:string;actor_id:string|null;created_at:string};
const draftFields = [
  ["step1","name","아이디어 이름"],["step1","source","출처"],["step1","url","출처 링크"],["step1","description","발견과 설명"],
  ["step2","principle","작동 원리"],["step2","strengths","강점"],["step2","limits","한계"],
  ["step3","idea_name","확장한 아이디어 이름"],["step3","application","활용 방법"],["step3","similar_ideas","유사한 아이디어"],["step3","feasibility_reason","실현 가능성 근거"],
  ["summary","overview","전체 요약"],["summary","thing","핵심 이름"],["summary","problem","핵심 필요"],
  ["execution","audience","대상 사용자"],["execution","scenario","사용 상황"],["execution","first_test","첫 실험"],["execution","success_metric","성공 기준"],
] as const;
export default function AdminAIEditor({session,members,messages,events}:{session:Session;members:Member[];messages:ConversationEntry[];events:Event[]}) {
  const router = useRouter();
  const [state,setState] = useState<SessionState>(session.state);
  const [recipient,setRecipient] = useState("");
  const [transferConfirmed,setTransferConfirmed] = useState(false);
  const [busy,setBusy] = useState(false);
  const [error,setError] = useState("");
  const [message,setMessage] = useState("");
  const labels = topicLabels(dialogueMode(state));
  const owner = members.find(member=>member.id===session.user_id)?.display_name || "이름 없는 사용자";
  async function send(action:"edit"|"transfer") {
    setBusy(true);setError("");setMessage("");
    try { const response=await fetch("/api/admin/ai",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,id:session.id,revision:session.revision,...(action==="edit"?{state}:{recipient})})}); const data=await response.json(); if(!response.ok)throw new Error(data.error); setMessage(action==="edit"?"수정 내용을 저장했어요.":"선택한 사용자에게 대화를 이동했어요. 기존 공유는 해제했어요."); router.refresh(); } catch(e){setError(e instanceof Error?e.message:"변경하지 못했어요.");}finally{setBusy(false);}
  }
  function draftValue(group:typeof draftFields[number][0], key:string) {const value=(state.draft?.content[group]??{}) as unknown as Record<string,unknown>;return typeof value[key]==="string"?value[key] as string:"";}
  function updateDraft(group:typeof draftFields[number][0],key:string,value:string){setState(old=>old.draft?{...old,draft:{...old.draft,content:{...old.draft.content,[group]:{...old.draft.content[group],[key]:value}}}}:old);}
  return <section className="min-w-0 rounded-2xl border border-border-default p-5 md:p-7"><h2 className="text-xl font-semibold">{session.state.draft?.title || "대화 상세"}</h2><p className="mt-2 text-sm leading-6 text-foreground/70">소유자: {owner} · 수정 {session.revision}회</p>
    <details open className="mt-6"><summary className="cursor-pointer text-base font-semibold">원문과 선택 답변</summary><div className="mt-4 space-y-5"><label className="block"><span className="mb-2 block text-sm font-medium">처음 적은 메모</span><textarea value={state.seed} maxLength={8000} onChange={e=>setState(old=>({...old,seed:e.target.value}))} className="ai-textarea" rows={5}/></label>{state.focusDirection!==undefined&&<label className="block"><span className="mb-2 block text-sm font-medium">실행 구체화 방향</span><textarea value={state.focusDirection} maxLength={2000} onChange={e=>setState(old=>({...old,focusDirection:e.target.value}))} className="ai-textarea" rows={3}/></label>}{state.answers.map((answer,index)=><label key={answer.topic} className="block"><span className="mb-2 block text-sm font-medium">{labels[answer.topic]}</span><span className="mb-2 block text-sm leading-6 text-foreground/70">{answer.question}</span><textarea value={answer.value} maxLength={16000} onChange={e=>setState(old=>({...old,answers:old.answers.map((a,i)=>i===index?{...a,value:e.target.value}:a)}))} className="ai-textarea" rows={3}/></label>)}</div></details>
    {state.question&&<details className="mt-6"><summary className="cursor-pointer text-base font-semibold">진행 중인 질문과 선택지</summary><div className="mt-4 space-y-4"><label className="block"><span className="mb-2 block text-sm">질문</span><textarea value={state.question.prompt} onChange={e=>setState(old=>({...old,question:old.question?{...old.question,prompt:e.target.value}:null}))} className="ai-textarea" rows={2}/></label><label className="block"><span className="mb-2 block text-sm">질문 이유</span><textarea value={state.question.reason} onChange={e=>setState(old=>({...old,question:old.question?{...old.question,reason:e.target.value}:null}))} className="ai-textarea" rows={2}/></label>{state.question.options.map((option,index)=><div key={option.id} className="space-y-2 rounded-xl border border-border-default p-3"><input aria-label={`선택지 ${index+1} 제목`} value={option.label} onChange={e=>setState(old=>({...old,question:old.question?{...old.question,options:old.question.options.map((o,i)=>i===index?{...o,label:e.target.value}:o)}:null}))} className="ai-input w-full"/><textarea aria-label={`선택지 ${index+1} 설명`} value={option.detail} onChange={e=>setState(old=>({...old,question:old.question?{...old.question,options:old.question.options.map((o,i)=>i===index?{...o,detail:e.target.value}:o)}:null}))} className="ai-textarea" rows={2}/></div>)}</div></details>}
    {state.draft&&<details className="mt-6"><summary className="cursor-pointer text-base font-semibold">정리본 수정</summary><p className="my-4 text-sm leading-6 text-foreground/70">원문이나 답변을 수정해도 정리본은 자동으로 달라지지 않아요. 내용이 맞는지 함께 검토해주세요. 기존에 공유한 정리본은 소유자가 다시 공유할 때 갱신돼요.</p><div className="space-y-4"><label className="block"><span className="mb-2 block text-sm font-medium">제목</span><input value={state.draft.title} onChange={e=>setState(old=>({...old,draft:old.draft?{...old.draft,title:e.target.value}:null}))} className="ai-input w-full"/></label>{draftFields.filter(([group])=>group!=="execution"||state.draft?.content.execution).map(([group,key,label])=><label key={`${group}.${key}`} className="block"><span className="mb-2 block text-sm font-medium">{label}</span><textarea value={draftValue(group,key)} onChange={e=>updateDraft(group,key,e.target.value)} className="ai-textarea" rows={3}/></label>)}{(["suggestions","open_questions"] as const).map(key=><label key={key} className="block"><span className="mb-2 block text-sm font-medium">{key==="suggestions"?"추가 제안":"확인할 내용"} · 항목마다 줄바꿈</span><textarea value={state.draft![key].join("\n")} onChange={e=>setState(old=>({...old,draft:old.draft?{...old.draft,[key]:e.target.value.split("\n").filter(Boolean)}:null}))} className="ai-textarea" rows={3}/></label>)}</div></details>}
    <div className="mt-6 flex justify-end"><button type="button" disabled={busy||state.seed.trim().length<5} onClick={()=>void send("edit")} className="ai-primary"><Save size={15}/>{busy?"저장 중…":"수정 내용 저장"}</button></div>
    <details className="mt-7 border-t border-border-default pt-6"><summary className="cursor-pointer text-base font-semibold">다른 사용자에게 이동</summary><p className="mt-3 text-sm leading-6 text-foreground/70">대화 전체의 소유자가 바뀌어요. 이전 소유자는 볼 수 없고, 기존 공유 링크도 비공개로 전환돼요.</p><label className="mt-4 block"><span className="mb-2 block text-sm">새 소유자</span><select value={recipient} onChange={e=>{setRecipient(e.target.value);setTransferConfirmed(false);}} className="ai-input w-full"><option value="">사용자를 선택해주세요</option>{members.filter(member=>member.id!==session.user_id).map(member=><option key={member.id} value={member.id}>{member.display_name||"이름 없는 사용자"}</option>)}</select></label><label className="mt-4 flex items-start gap-2 text-sm leading-6"><input type="checkbox" checked={transferConfirmed} onChange={e=>setTransferConfirmed(e.target.checked)} className="mt-1.5 accent-[#2563eb]"/>소유권 변경과 공유 해제를 확인했어요.</label><button type="button" disabled={busy||!recipient||!transferConfirmed} onClick={()=>void send("transfer")} className="ai-secondary mt-4"><ArrowRightLeft size={15}/>선택한 사용자에게 이동</button></details>
    {error&&<p role="alert" className="mt-5 text-base text-red-700">{error}<button type="button" onClick={()=>router.refresh()} className="ml-2 underline">최신 기록 불러오기</button></p>}{message&&<p role="status" className="mt-5 text-base">{message}</p>}
    <details className="mt-7 border-t border-border-default pt-6"><summary className="cursor-pointer text-base font-semibold">전체 대화 기록</summary><div className="mt-5">{messages.length?<ConversationEntries messages={messages}/>:<ol className="space-y-4">{(state.history??state.answers).map((a,index)=><li key={index} className="rounded-xl bg-surface p-4"><p className="font-medium leading-7">{a.question}</p><p className="mt-2 whitespace-pre-wrap text-base leading-7">{a.value}</p></li>)}</ol>}</div></details>
    {session.state.draft&&<details className="mt-7"><summary className="cursor-pointer text-base font-semibold">현재 정리본 보기</summary><div className="mt-5"><DraftPreview draft={session.state.draft}/></div></details>}
    <details className="mt-7"><summary className="cursor-pointer text-base font-semibold">관리자 변경 이력</summary><ul className="mt-3 space-y-3 text-sm leading-6 text-foreground/75">{events.map(event=><li key={event.id}>{({edit:"내용 수정",transfer:"소유자 이동",role:"관리자 권한 변경"} as Record<string,string>)[event.action]} · {members.find(p=>p.id===event.actor_id)?.display_name||"관리자"} · {new Date(event.created_at).toLocaleString("ko-KR")}</li>)}{!events.length&&<li>아직 관리자 변경 이력이 없어요.</li>}</ul></details>
  </section>;
}
